### ISSUE TITLE
Issue with running the python

### ISSUE THREAD

**Issue by DannyBrock123** [darkerego/pyloris#1]
C:\Users\marka\OneDrive\Desktop\pyloris-master>python attack.py -h
  File "C:\Users\marka\OneDrive\Desktop\pyloris-master\attack.py", line 18
    print ''' usage : python attack.py [-t] [-c] http://www.baidu.com/
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by furjac** [comment]
@DannyBrock123 its python 2 run using python 2

**Comment by darkerego** [comment]
This is ancient, when I get a chance I will clean it up a bit

**Comment by furjac** [comment]
@darkerego yep it will be great if u did that

**Comment by darkerego** [comment]
> @darkerego yep it will be great if u did that

Okay. I spent two hours rewriting this for you. It is now asynchronous and probably more powerful. Not sure that there's going to be many servers out there that this will work on, as it is ancient stuff, but here you go!
